config/routes.rb
Rails.application.routes.draw do

  get 'sections/favorites' => 'sections#favorites', as: :favorites

  resources :sections do
    resources :subscriptions do
      resources :articles
    end
  end

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  post 'users/login' => 'users#login'
  delete 'users/logout' => 'users#logout'
  get 'users/:id' => 'users#show', as: :user
  put 'story/:id' => 'stories#update', as: :favorite_stories
  patch 'story/:id' => 'stories#update'

  root 'sections#show'

end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to	:user
  has_many  :subscriptions, dependent: :delete_all
  has_many :stories
  has_many :articles, through: :subscriptions

	validates	:title, uniqueness: { scope: :user }, presence: true

  def cluster_similar_stories
    todays_articles = articles.where("articles.created_at > now() - interval '23 hour'")
    clusters = cluster_articles(todays_articles)
    todays_stories = clusters_to_stories(clusters)
  end

  def todays_stories
    recent_stories = stories.where("stories.created_at > now() - interval '23 hour'").order("stories.created_at DESC").limit(169)
    assign_sizes(order_stories(recent_stories))
  end

  private
  def cluster_articles(articles)
    articles = articles.map { |x| x }
    clusters = []
    while articles.length > 0
      n = 0
      clusters << []
      while n < articles.length
        # p "n: #{n}"
        if articles[n].is_similar_to?(articles[-1])
          clusters[-1] << articles.delete_at(n)
        else
          n += 1
        end
      end
    end
    clusters
  end

  def clusters_to_stories(clusters)
    story_clusters = clusters.map do |story_cluster|
      # sort story_cluster so preferred stories are first
      stories.create(preferred_story: story_cluster[0], articles: story_cluster)
    end
    story_clusters.reverse!
    get_imgs(story_clusters)
    assign_sizes(order_stories(story_clusters))
    # Split stories into groups with images and without images
    # build an array of size groups out of those
    # shuffle then flatten?

    # So we kind of have a chicken//egg scenario here. Being able to grab images informs the size of stories
    # but at the same time grabbing images takes really long so being able to figure out the sizes of stories
    # first would speed that up

  end

  def get_imgs(story_cluster)
    number_of_images_needed = ((3 * story_cluster.length) / 13) + partial_patten_offset
    story_cluster.each do |story|
      story.fetch_img
      if story.has_image?
        number_of_images_needed -= 1
      end
      break if number_of_images_needed == 0
    end
  end

  def order_stories(story_clusters)
    with_img = story_clusters.select { |story| story.has_image? }
    without_img = story_clusters.reject { |story| story.has_image? }

    ordered_stories = Array.new(story_clusters.length)
    ordered_stories.each_with_index do |story, i|
      if (i % 13 == 0 || i % 13 == 4 || i % 13 == 8) && !with_img.empty?
        ordered_stories[i] = with_img.pop
      elsif !without_img.empty?
        ordered_stories[i] = without_img.pop
      else
        ordered_stories[i] = with_img.pop
      end
    end
    ordered_stories
  end

  def assign_sizes(ordered_stories)
    ordered_stories.each_with_index do |story, i|
      case i % 13
      when 0
        story.size = "splash"
      when 4, 8
        story.size = "big"
      when 1, 2, 3, 7, 11, 12
        story.size = "medium"
      else
        story.size = "small"
      end
      story.save
    end
  end

  def partial_patten_offset
    case stories.length % 13
    when 0,1,2,3
      1
    when 4,5,6,7
      2
    else
      3
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :authorize_user_logged_in, except: :show
  def index
    @sections = current_user.sections
    @section = Section.new
    @page_name = "Edit Sections"
    @subscription = @section.subscriptions.new
    # @feed = Feed.new
  end

	def show
    if user_logged_in?
      @active_section = Section.find_by(id: params[:id]) || Section.find_by(title: 'Default')
      @sections = current_user.sections
    	@stories = @active_section.todays_stories
      @page_name = @active_section.title
      @stories = Kaminari.paginate_array(@stories).page(params[:page]).per(26)
      respond_to do |format|
        format.js { render text: "HELLO!"}
        format.html
      end
    else
      @section = Section.find_by(title: 'Default')
      @stories = Kaminari.paginate_array(@section.todays_stories).page(params[:page]).per(13)
      @page_name = "Top Stories"
      respond_to do |format|
        format.html
        format.js
      end
    end
	end

  def favorites
    @sections = current_user.sections
    @stories = Kaminari.paginate_array(current_user.favorited_stories).page(params[:page]).per(26)
    @page_name = "Saved Articles"
    render :show
  end

  #literally everything after here is subject to change based on the views

  def new
    @section = Section.new
  end

  def create
    @section = current_user.sections.build(section_params)
    @subscription = Subscription.new
    if @section.save
      if request.xhr?
        render partial: 'sections/section', locals: { section: @section }
      else
        redirect_to sections_path
      end
    else
      if request.xhr?
        render json: @section.errors.full_messages
      else
        redirect_to sections_path
      end
    end
  end

  def edit
    @sections = current_user.sections
    @section = Section.find(params[:id])
    @page_name = "Rename Section"
    if request.xhr?
      render :edit, layout: false
    end
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      if request.xhr?
        render nothing: true
      else
        redirect_to sections_url
      end
    else
      if request.xhr?
        render json: @section.errors.full_messages
      else
        redirect_to sections_url
      end
    end
  end

  def destroy
    p 'DESTROY DESTROY'
    Section.find(params[:id]).destroy
    if request.xhr?
      render nothing: true
    else
      redirect_to :back
    end
  end

  private
    def section_params
      params.require(:section).permit(:title)
    end

    def user_default_section
      user_logged_in? ? current_user.sections.first : nil
    end
end

app/views/sections/_section.html.erb
<div class="list-left section-box">
  <span class="vertical-center">
    <%= form_tag("/sections/#{ section.id }", method: :delete, class: 'inline delete-section') do %>
      <%= submit_tag 'Delete' %>
    <% end %>
    <%= form_tag(edit_section_path( section ), method: :get, class: 'inline rename-section') do %>
      <%= submit_tag 'Rename' %>
    <% end %>
  </span>

  <span class="mdl-typography--display-2 inline">
    <%= link_to "#{ section.title }", section_path( section ) %>
  </span>
</div>

<div class="pd-2">
  <% if @subscription.errors.any? %>
    <% @subscription.errors.full_messages do |msg| %>
      <p class="center bold mdl-color--deep-purple-500 mdl-color-text--black-A700"><%= msg %></p>
    <% end %>
  <% end %>

  <p>
    <%= form_for @subscription, url: "/sections/#{section.id}/subscriptions", method: 'POST' do |f| %>
      <%= f.text_field :name, class: 'list-left w-50', placeholder: 'Subscription Name' %>
      <%= f.text_field :feed, class: 'list-left w-50', placeholder: 'RSS feed' %>
      <%= f.submit value: 'Add Feed', class: 'inline fl-r' %>
     <% end %>
  </p>

app/views/sections/_stories.html.erb
<% stories.each do |story| %>
  <%= render partial: "application/article_#{ story.size }", locals: { story: story } %>
<% end %>

app/views/sections/default.html.erb
<div class="mdl-grid">
  <% @stories.each do |story| %>
    <%= render partial: "application/article_#{ story.size }", locals: { story: story } %>
  <% end %>
</div>

app/views/sections/edit.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col-phone round mdl-cell--8-col center">
    <div class="section_box"><p>
      <%= form_for @section do |f| %>
        <%= f.text_field :title, placeholder: 'Section name' %>
        <%= f.submit value: 'Rename' %>
      <% end %>
    </p></div>
  </div>
</div>

app/views/sections/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--4-col-phone round mdl-cell--8-col center-box pd-4">
    <p>
      <%= form_for @section, method: 'POST' do |f| %>
        <%= f.text_field :title, class: 'list-left w-50', placeholder: 'Section name' %>
        <%= f.submit value: 'Add Section', class: 'inline fl-r' %>
      <% end %>
    </p>

    <% @sections.each do |section| %>
      <%= render partial: 'sections/section', locals: { section: section } %>

      <% section.subscriptions.each do |subscription| %>
        <%= render partial: 'subscriptions/subscription', locals: { section: section, subscription: subscription } %>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/sections/show.html.erb
<div class="mdl-grid">
  <% @stories.each do |story| %>
    <%= render partial: "application/article_#{ story.size }", locals: { story: story } %>
  <% end %>

  <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone round center button-height" id="paginator">
    <%= paginate @stories %>
  </div>
</div>