config/routes.rb
Rails.application.routes.draw do

  get 'sections/favorites' => 'sections#favorites', as: :favorites

  resources :sections do
    resources :subscriptions do
      resources :articles
    end
  end

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  post 'users/login' => 'users#login'
  delete 'users/logout' => 'users#logout'
  get 'users/:id' => 'users#show', as: :user
  put 'story/:id' => 'stories#update', as: :favorite_stories
  patch 'story/:id' => 'stories#update'

  root 'sections#show'

end

app/models/subscription.rb
require 'open-uri'
require 'mechanize'
require 'net/http'

class Subscription < ActiveRecord::Base
	has_many		:articles, through: :feed
	has_many		:stories, through: :user
	has_one			:user, through: :section
	belongs_to 	:section
	belongs_to  :feed

  validates :name, presence: :true, uniqueness: { scope: :section }
  validates :feed, presence: :true
  validates_associated :feed

	def assign_feed=(feed_url)
		self.feed = Feed.where(feed_url: feed_url).first_or_create
	end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
	def new
		@subscription = Subscription.new
	end

	def create
		@section = Section.find_by(id: params[:section_id])
		@subscription = Subscription.new(subscription_params)
		# begin
			p '*' * 50
			p params
			feedssssss = Feed.find_or_create_by(feed_url: params['subscription']['feed'])
			p feedssssss
			p '-' * 50
			@subscription.assign_attributes(section: @section, feed: feedssssss)
			p '*' *50
		# rescue NoMethodError
			# @subscription.assign_attributes(section: @section, feed: Feed.new)
		# end
		if @subscription.save
			if request.xhr?
				render partial: 'subscriptions/subscription', locals: { section: @section, subscription: @subscription }
			else
				redirect_to sections_path
			end
		else
			if request.xhr?
				render json: @subscription.errors.full_messages
			else
				render "sections/index"
			end
		end
	end

	def edit
		@subscription = Subscription.find(params[:id])
		if request.xhr?
			render partial: 'subscriptions/edit_form', locals: { subscription: @subscription }
		else
		end
	end

	def update
		@subscription = Subscription.find(params[:id])
		if @subscription.update_attributes(subscription_params)
			if request.xhr?
				render nothing: true
			else
				redirect_to "sections/index"
			end
		else
			if request.xhr?
				render json: @subscription.errors.full_messages
			else
				flash[:errors] = @subscription.errors.full_messages
				redirect_to "sections/index"
			end
		end
	end

	def destroy
		Subscription.find_by(id: params[:id]).destroy
		if request.xhr?
			render nothing: true
		else
			redirect_to :back
		end
	end

	private
		def subscription_params
			params.require(:subscription).permit(:name)
		end
end

app/views/subscriptions/_edit_form.html.erb
<div class="section_box subscription-edit-form"><p>
  <%= form_for subscription, url: section_subscription_path(subscription.section, subscription) do |f| %>
    <%= f.text_field :name, value: subscription.name, placeholder: 'Subscription name' %>
    <%= f.submit value: 'Rename' %>
  <% end %>
</p></div>

app/views/subscriptions/_subscription.html.erb
<div class="subscription list-left feed-box">
  <span class="vertical-center">
    <%= form_tag(section_subscription_path(section, subscription), method: :delete, class: 'inline delete-subscription') do %>
      <%= submit_tag 'Delete' %>
    <% end %>
    <%= form_tag(edit_section_subscription_path( section, subscription ), method: :get, class: 'inline edit-subscription') do %>
      <%= submit_tag 'Rename' %>
    <% end %>
  </span>

  <span class="mdl-typography--title inline">
    <%= subscription.name %>
  </span>
</div>

app/views/subscriptions/show.html.erb
<ul>
	<% @articles.each do |article| %>
		<li>
			<%= link_to "#{ article.title }", section_subscription_article_path(@section, @subscription, article) %>
		</li>
	<% end %>
</ul>