config/routes.rb
Rails.application.routes.draw do

  get 'sections/favorites' => 'sections#favorites', as: :favorites

  resources :sections do
    resources :subscriptions do
      resources :articles
    end
  end

  get 'users/new' => 'users#new'
  post 'users' => 'users#create'
  post 'users/login' => 'users#login'
  delete 'users/logout' => 'users#logout'
  get 'users/:id' => 'users#show', as: :user
  put 'story/:id' => 'stories#update', as: :favorite_stories
  patch 'story/:id' => 'stories#update'

  root 'sections#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def reset_login_error
      session['login_error'] = false
    end

    def user_logged_in?
      !session['user_id'].nil? && User.find_by(id: session['user_id'])
    end

    def current_user
      user_logged_in? ? User.find(session['user_id']) : nil
    end

    def authorize_user_logged_in
      redirect_to root_path unless user_logged_in?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_logged_in?
      !session['user_id'].nil? && User.find_by(id: session['user_id'])
    end

    def current_user
      user_logged_in? ? User.find(session['user_id']) : nil
    end
end

app/views/application/_article_big.html.erb
<div class="mdl-cell mdl-cell--4-col-phone round mdl-cell--8-col <%= 'talked-about' if story.other_sources.count > 1 %>">
	<%= image_tag(story.preferred_story.img_link, width: '200', class: "med_box_image fl-r") %>

  <%= render partial: "application/more_button", locals: {story: story} %>


  <%= render partial: "application/more_button", locals: {story: story} %>

  <span class="mdl-typography--title"><%= link_to story.preferred_story.title, story.preferred_story.url, target: "_blank" %></span><br>

  <span class="mdl-typography--body-1"><%= story.preferred_story.summary %></span><br>

  <span class="mdl-typography--body-1 mdl-color-text--grey-500"><%= story.preferred_story.news_source(story.section_id) %></span>

  <%= render partial: "application/save_button", locals: {story: story} %>

  <%= render partial: "application/related", locals: {story: story} %>
</div>

app/views/application/_article_medium.html.erb
<div class="mdl-cell mdl-cell--4-col-phone round mdl-cell--4-col <%= 'talked-about' if story.other_sources.count > 1 %>">
  <%= render partial: "application/more_button", locals: {story: story} %>

  <span class="mdl-typography--title"><%= link_to story.preferred_story.title, story.preferred_story.url, target: "_blank" %></span><br>

  <span class="mdl-typography--body-1 mdl-color-text--grey-500"><%= story.preferred_story.news_source(story.section_id) %></span>

  <%= render partial: "application/save_button", locals: {story: story} %>

  <%= render partial: "application/related", locals: {story: story} %>
</div>

app/views/application/_article_small.html.erb
<div class="mdl-cell mdl-cell--4-col-phone round mdl-cell--2-col <%= 'talked-about' if story.other_sources.count > 1 %>">
  <%= render partial: "application/more_button", locals: {story: story} %>

  <span class="mdl-typography--body-1"><%= link_to story.preferred_story.title, story.preferred_story.url, target: "_blank" %></span><br>

  <span class="mdl-typography--body-1 mdl-color-text--grey-500"><%= story.preferred_story.news_source(story.section_id) %></span>

  <%= render partial: "application/save_button", locals: {story: story} %>

  <%= render partial: "application/related", locals: {story: story} %>
</div>

app/views/application/_article_splash.html.erb
<div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-phone round image" style="background-image: url('<%= story.preferred_story.img_link %>');">
  <%= render partial: "application/more_button", locals: {story: story} %>

  <div class="photo-overlay">
    <span class="mdl-typography--display-2 mdl-color-text--white"><%= link_to story.preferred_story.title, story.preferred_story.url, target: "_blank" %></span><br>
    <span class="mdl-typography--headline mdl-color-text--white"><%= story.preferred_story.summary %></span><br>
    <span class="mdl-typography--headline mdl-color-text--grey-500"><%= story.preferred_story.news_source(story.section_id) %></span>

    <%= render partial: "application/save_button", locals: {story: story} %>

    <%= render partial: "application/related", locals: {story: story} %>
  </div>
</div>

app/views/application/_bannerdrawer.erb
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-color--orange-300">
    <span id="banner" class="mdl-typography--display-3"><%= page_name %></span>
  </header>

  <div class="mdl-layout mdl-js-layout mdl-layout--drawer mdl-layout--overlay-drawer-button">
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title"><%= link_to "Edit Sections", sections_path %></span>
      <nav class="mdl-navigation">
        <% sections.each do |section| %>
          <li>
            <%= link_to "#{ section.title }", section_path( section ), class: "mdl-navigation__link" %>
          </li>
        <% end %>
          <li>
            <%= link_to "Saved", favorites_path, class: "mdl-navigation__link" %>
          </li>
      </nav>
    </div>
  </div>

app/views/application/_bannernodrawer.erb
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-color--orange-300 mdl-layout__header--scroll">
    <span id="banner" class="mdl-typography--display-3"><%= page_name %></span>
  </header>

app/views/application/_drawernobanner.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">

  <header class="mdl-layout__header mdl-color--orange-300">
    <span id="banner" class="mdl-typography--display-3"><%= page_name %></span>
  </header>

app/views/application/_login.html.erb
<% if flash['login_error'] %>
  <p class="center bold mdl-color--deep-purple-500 mdl-color-text--black-A700">Incorrect Email or Password</p>
<% end %>

<div class="login_box">
  <%= form_tag("/users/login", method: 'POST', id: 'login-form') do %>
    <%= text_field_tag 'email', nil, placeholder: 'Email' %>
    <%= text_field_tag 'password', nil, placeholder: 'Password' %>
    <%= submit_tag 'Login' %>
  <% end %>
</div>

app/views/application/_masthead.html.erb
<div class="masthead">
  <p class="logo">
    <%= link_to image_tag("eelogo.jpg", alt: "The Evening Edition"), root_path %>
  </p>

  <p>
    <span class="mdl-typography--title"><%= Time.now.strftime("For %B %d, %Y") %></span>
  </p>

  <div class="login mdl-color--orange-900">
    <span class="mdl-typography--caption">
      <% if user_logged_in? %>
        Personalized for <%= current_user.email %> / <%= link_to "Log out", users_logout_path, method: :delete, id: 'logout-link' %>
      <% else %>
        Updated each day at 5 pm Chicago local time.<br>
        Members receive personalized subscriptions, sections, and delivery times.
        <%= link_to "Create a free account now.", users_new_path, id: 'sign-up'%><br>
        <%= render 'login' %>
      <% end %>
    </span>
  </div>
</div>

app/views/application/_more_button.html.erb
<% unless story.other_sources.empty? %>
	<button id="<%= story.preferred_story.id %>" class="mdl-button mdl-js-button mdl-button--icon mdl-color--orange-300">
	    <i class="material-icons">more_vert</i>
	</button>
<% end %>

app/views/application/_related.html.erb
<ul for="<%= story.preferred_story.id %>" class="mdl-menu mdl-menu--bottom-right mdl-js-menu">
  <p class="mdl-menu__item">Related:</p>
  <% story.other_sources.each do |related| %>
    <li class="mdl-menu__item mdl-color-text--grey-500"><%= related.news_source(story.section_id) %>--<span class=""><%= link_to related.title.split(" ").slice(0..5).push("...").join(" "), related.url, target: "_blank" %></span></li>
  <% end %>
</ul>

app/views/application/_save_button.html.erb
<% if user_logged_in? %>
  <% if story.favorited == true %>
    <%= form_tag(favorite_stories_path( story.id ), method: :put, value: false, class: 'inline save_story_button') do %>
      <%= hidden_field_tag 'favorited', 'false' %>
      <%= submit_tag ' | Unsave', class: 'save_button' %>
    <% end %>
  <% else %>
    <%= form_tag(favorite_stories_path( story.id ), method: :put, value: true, class: 'inline save_story_button') do %>
      <%= hidden_field_tag 'favorited', 'true' %>
      <%= submit_tag ' | Save', class: 'save_button' %>
    <% end %>
  <% end %>
<% end %>